---
- name: Install fastfetch on Debian 12 PC + Raspberry Pi
  hosts: all
  become: yes
  tasks:
    - name: Install required tools for both methods
      ansible.builtin.apt:
        name:
          - curl
          - tar
          - git
          - cmake
          - gcc
          - g++
          - pkg-config
          - libwayland-dev
        state: present
        update_cache: yes

    - name: Detect system architecture
      ansible.builtin.command: dpkg --print-architecture
      register: system_arch
      changed_when: false

    - name: Get latest fastfetch release data
      ansible.builtin.uri:
        url: https://api.github.com/repos/fastfetch-cli/fastfetch/releases/latest
        return_content: yes
      register: release_data

    - name: Search for .deb URL matching architecture
      set_fact:
        fastfetch_deb_url_list: >-
          {{
            release_data.json.assets
            | selectattr('name', 'search', system_arch.stdout + '.deb')
            | map(attribute='browser_download_url')
            | list
          }}

    - name: Set .deb URL if available
      set_fact:
        fastfetch_deb_url: "{{ fastfetch_deb_url_list[0] }}"
      when: fastfetch_deb_url_list | length > 0

    - name: Download and install from .deb if available
      block:
        - name: Download fastfetch .deb
          ansible.builtin.get_url:
            url: "{{ fastfetch_deb_url }}"
            dest: /tmp/fastfetch.deb
            mode: '0644'

        - name: Install fastfetch .deb
          ansible.builtin.apt:
            deb: /tmp/fastfetch.deb
      when: fastfetch_deb_url is defined

    - name: Build from source if no .deb available
      block:
        - name: Clone fastfetch source
          ansible.builtin.git:
            repo: https://github.com/fastfetch-cli/fastfetch.git
            dest: /tmp/fastfetch-src
            depth: 1

        - name: Create build directory
          ansible.builtin.file:
            path: /tmp/fastfetch-src/build
            state: directory

        - name: Compile fastfetch
          ansible.builtin.shell: |
            cmake ..
            make -j"$(nproc)"
          args:
            chdir: /tmp/fastfetch-src/build

        - name: Install compiled fastfetch
          ansible.builtin.shell: make install
          args:
            chdir: /tmp/fastfetch-src/build
      when: fastfetch_deb_url is not defined
