---
- name: Uninstall Fastfetch (multi-distro + multi-arch)
  hosts: all
  become: true
  gather_facts: true

  vars:
    arch_map:
      x86_64: "amd64"
      amd64: "amd64"
      i386: "i386"
      i686: "i386"
      armv7l: "armhf"
      armhf: "armhf"
      aarch64: "arm64"
      arm64: "arm64"

  tasks:

    - name: Map system architecture
      set_fact:
        system_arch: "{{ arch_map[ansible_architecture] | default('unknown') }}"

    - name: Debug detected info
      debug:
        msg: "Distro: {{ ansible_distribution }} ({{ ansible_distribution_release | default('n/a') }}) | Arch: {{ system_arch }}"

    # --- Debian/Ubuntu family ---
    - name: Remove Fastfetch (Debian/Ubuntu)
      apt:
        name: fastfetch
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Autoremove dependencies (Debian/Ubuntu)
      apt:
        autoremove: yes
      when: ansible_os_family == "Debian"

    # --- RedHat family ---
    - name: Remove Fastfetch (RHEL/CentOS/Fedora/Rocky/Alma)
      package:
        name: fastfetch
        state: absent
