---
- name: Uninstall Fastfetch (multi-distro + multi-arch)
  hosts: all
  become: true
  gather_facts: true

  vars:
    arch_map:
      x86_64: "amd64"
      amd64: "amd64"
      i386: "i386"
      i686: "i386"
      armv7l: "armhf"
      armhf: "armhf"
      aarch64: "arm64"
      arm64: "arm64"

  tasks:

    - name: Map system architecture
      set_fact:
        system_arch: "{{ arch_map[ansible_architecture] | default('unknown') }}"

    - name: Debug detected info
      debug:
        msg: "Distro: {{ ansible_distribution }} ({{ ansible_distribution_release | default('n/a') }}) | Arch: {{ system_arch }}"

    # --- Debian/Ubuntu family ---
    - name: Remove Fastfetch (Debian/Ubuntu)
      apt:
        name: fastfetch
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Autoremove dependencies (Debian/Ubuntu)
      apt:
        autoremove: yes
      when: ansible_os_family == "Debian"

    # --- RedHat family ---
    - name: Remove Fastfetch (RHEL/CentOS/Fedora/Rocky/Alma)
      package:
        name: fastfetch
        state: absent
      when: ansible_os_family == "RedHat"

    # --- Arch family ---
    - name: Remove Fastfetch (Arch/Manjaro)
      community.general.pacman:
        name: fastfetch
        state: absent
      when: ansible_distribution in ["Archlinux", "ManjaroLinux"]

    # --- openSUSE family ---
    - name: Remove Fastfetch (openSUSE/SLES)
      community.general.zypper:
        name: fastfetch
        state: absent
      when: ansible_os_family == "Suse"

    # --- Fallback cleanup ---
    - name: Remove Fastfetch binary manually (if present)
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /usr/local/bin/fastfetch
        - /usr/bin/fastfetch
      when: ansible_os_family not in ["Debian", "RedHat", "Suse"] and
            ansible_distribution not in ["Archlinux", "ManjaroLinux"]
